INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Richard Abadie', 'Richard.abadie2@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean Pierrre Adam', 'jeanpierreadam3@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean François Allais', 'jeff.allais@hotmail.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Nouchka Alles', 'nouchkavercors@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('sophie amable', 'sophie.amable@yacht-concept.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('olivier Amiot', 'olivieramiot@gmx.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Paco Andreo', 'paco-andreo@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean Larie Andres', 'andres.juan@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Pierre olivier Antoine', 'antoine_pierreo@hotmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Pauline Aqntoine', 'paulineantoine1@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Laurent Armeneau', 'laurent.armenaud@laposte.net');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jeanne Arsac', 'arsacjeanne@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Karine Audouin', 'karine.audoin@hotmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Ambroise Aubert', 'ambroiseaubert@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Françis AZEVEDO', 'azevedo_francis@hotmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES(' ', 'yves-aumont@club-internet.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Yves AUMONT', 'yves-aumont@laposte.net');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Anne  Auroux', 'anne.auroux@passeurdecoute.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Pierre Azeau', 'pierre.azeau@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Christophe Bacon', 'Christophe.BACON@saipem.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Roxane Balan', 'roxanebalan@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Patrick  Ballu', 'Patrick.Ballu@cadexi.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Marine Bardou', 'm.bardou@stphilibert.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Coline Barraud', 'colinebarraud@hotmail.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Rébecca Baudrier', 'rebecca.baudrier.archi@gmail.com');
-- INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Léa  Bazière', 'lea.baziere@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Léa Bazière', 'lea.baziere@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Céline Beaudon', 'celine.beaudon@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('antoine beauquin', 'antoine.beauquin@outlook.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Sandrine Benac', 'geronimo-8@live.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Manon Benard', 'isseo.asso@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Pierre Benard', 'pierrebenard@hotmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Remy Bernard', 'chausey1@free.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Serge benard', 'sergebenard7@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Philippe Benoiton', ' philippe.benoiton@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Patrick Benoiton ', 'patbenoiton@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Calixte Berger', 'CalixteBERGER@hotmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('regis Berleur', 'regis.berleur@ventdebout.be');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean Berthias', 'jeanberthias@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('René Berson', 'rene.berson@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Franck Berson', 'Franck.BERSON@bpgo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Christelle Besson', 'krystelle.besson@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Nicolas Bidon', 'nicogliss46@hotmail.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Julie Bignon', 'julie_bignon@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Louise Bigot', 'louise.bigot21@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Marine Billie', 'billiemarine@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('christian Binie', 'christbint@hotmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Romain Blanc', 'romainblanc7@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Guillaume  Blanc ', 'Guillaume.blanc@posteo.net');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Cyril Blancart', 'cyril.blancart@hotmail.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Pierre Blevin', 'blevin.pierre@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Catherine Boiteux', 'chevreriedelapoterie@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Mico Bolo', 'mbolonantes@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Julien Bonnefoy', 'julien.bonnefoy@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Marie aimée Bonnefoy', 'ma.bonnefoy@charentelibre.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Christelle Bordet', 'Christelle.bordetbonnefoy@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Marie Odile Botti', 'marieodilebotti@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Guillaume Bouan', 'bouan.g@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Christophe Bourdy', 'chbourdy@hotmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Benoit Boutry', 'd.b.services.bb@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Laurent Brochard', 'l.brochard.archi@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Christine Briand', 'christine.briand@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Bernard Brignon', 'brignon.bernard@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Julie Brossard', 'yl6591@hotmail.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Francis  Bucelle', 'francis.brucelle@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Patrice Bujedo', 'patrice.vnd@cegetel.net');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Emma Calvet', 'emma34380@hotmail.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Tiago Campos', 'tiagocampostc@hotmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('antoine Campos', 'atelier.antoinecampos@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('thierry Cantau', 'cantauthierry@hotmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Gilles Castel', 'gsirgc@gsir.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Laurent CAUCHY', 'coherence.ing@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean-Pierre  CAVÉ', 'jpc578@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Colin Chaballier', 'Colin.chaballier@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Aurelie Chaballier ', 'Aurelie.chaballier@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Catherine Chabaud', 'catherine.chabaud@europarl.europa.eu');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Brieuc Chaboisson', 'brieucchaboisson98@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('coline chabran', 'colinechabran@sfr.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Ninon Chatard', 'ninonp64@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('JM Chauvet', 'jmca@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Adrien Chatel', 'adrien.chatel@hotmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Fanny Chaussier', 'fchaussier@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Thierry Chevillon', 'tchevillon@robinmarine.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Raphaël Chenoir', 'chenoir.raphael@live.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Thierry Cherpitel', 'thierry.cherpitel56@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean-François Chesné', 'j-f.chesne@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Pauline Clin', 'clin.pauline@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Florence COCAUD MIENS', 'florencecocaud@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Phlippe  Coindreau', 'philippe.coindreau@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Laurence Coroller', 'laurence.corroler@editions-lariviere.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Clémence Colimard', 'ccolimard@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('louis marie Couetoux', 'lmcouetoux@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('ségolene Cozanet', 'segolene.49@hotmail.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean Christophe Crasnier', 'jc@seaviewprogress.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Denis Cuirinier', 'denis.cuirinier@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Abri Dalu', 'Arbri1994daiu@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Anne  De Bagneaux-Savatier  ', 'annedebagneaux-savatier@uncl.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Xavier De Becque', 'xavier.debec@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('François de Champs', 'francois.de.champs@hotmail.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Clara de Gasquet', 'claradegasquet@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('antoine De Guibert', 'deguibert.bene@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Maxime Deguibert', 'peremax72@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Dominique marie Deguillebon de resnes', 'dmgbnrn@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Camille Delabaere', 'camilledelabaere@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Adele Delahaye', 'adele.delahaye@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Hubert De la Reiviere', 'hubertdelariviere@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Dominique De Ponsay', 'dominique.deponsay@fondation-patrimoine.org');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Didier De Puyraymond', 'didier-de.puyraimond@tactiques.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Bernard  De Ravignan', 'marmajour@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Eric Dewolbock', 'eric.de.wolbock@me.com');
-- INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Camille Delabaere', 'camilledelabaere@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Claire Delacotte', 'clairedelacotte@live.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES(' Delfosse', 'prdelfosse@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('guillaume Deligniere', 'guillaume@noviomo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Gonzague Delval', 'gonzague.delval@sfr.fr');
-- INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Dominique Deponsay', 'Dominique.deponsay@fondation-patrimoine.org');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jules Depreaux', 'jules.despreaux@amer-mediterranee.org');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Christian Devaux', 'ch.devaux@icloud.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Itzel Diaz', 'itzeldiaz@yahoo.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('stéphane Dierick', 'stephane.dierick@sailcoop.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Lucie Dogramadjian', 'Lucie.dogramadjian@gmail.com');
-- INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jerome Dormois', 'jeromedormois@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Carole Dormoy', 'cdormoy@free.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Guillaume Donval', 'mmdonval@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Marie morgane Donval', 'guillaume.donval@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Marie Pierre Donval', 'mapieducap@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jérome Dormois', 'jeromedormois@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Hortense Doumic', 'hortense.lp@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Hippolyte Dreyfus ', 'hippolytedreyfus@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Nicholas Dulauroy', 'ndulauroy@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Marion Duroselle', 'marionduroselle@hotmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Thomas Durant', 'tdurand@nautipark.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Juliette EME', 'juliette.eme.cp@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Maxime Ehrenmann', 'ehrenmannm@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Patricia Favre', 'Patricia Favre ');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Denis Fauvet', 'd.fauvet@sailing-atlantic.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('AXELLE FAUVEL', 'axellefauv11@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Marc Flye', 'marcflye@aol.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('alice Flot', 'alice.flot@outlook.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Hubvert Follenfant', 'follenfant.hubert@neuf.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES(' Foucher-Poignat', 'foucher-poignat@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('augustin Fouquet d\'herouel', 'augustin.fdherouel@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('loic Fournier-Foch', 'loic.ff@teamwinds.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Marine  Gabbay', 'marinebulles@outlook.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('baptiste galli', 'gallibaptiste8@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Pierrick Garenne', 'pgarenne@grand-pavois.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Alain Garcia', 'garciaalain299@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jerome Garnier', 'expert.maritime.garnier@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Wenceslas Gasse', 'contact@voyageenpatrimoine.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Stephane Gateau', 'mobydicks.sail@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Lara Gatineau', 'lara.gatineaubochard.jd@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('C Gautier', 'c.gautier@compagniedesportsdumorbihan.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Regis Germain', 'germain.regis@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Marie Celine GUIGO', 'accueil.kernevest.bzh@outlook.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Frédéric  Gougeon', 'fredgougeon@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Didier Gregory', 'didier.greggory@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Basile Gueulle', 'basile.gueulle@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('david Guigue', 'david.contact2106@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('arnaud Guyot-sonnest', 'ia.guyot-sionnest@outlook.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Elisa Guizouarn ', 'elisa.guizouarn@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Paul GURY', 'paul.gury@editions-lariviere.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Alain Hahusseau ', 'alain.hahusseau@sfr.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Myriam Haquin Pahun', 'haquin2@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Meriem Hammi', 'rayondesoleilmh@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Fabiola Hamon', 'hamonf08@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Marie Pierre Hammon Pellen', 'Hammonpellen.avocat@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Claire hannecart', 'claire.hannecart@protonmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Gwenolé Harvard', 'guenole.havard@decathlon.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Benoît  Hochart', 'Benhoch123@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Michel Horellou', 'michelhorellou@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Mike Horn', 'mike@mikehorn.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Stéphane Hupin', 'stephanehupin@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Stephane  Huppin', 'yachtsdupatrimoine@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Lorraine Jaccot', 'lorraine.jacquot@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Gwendal JAFFRY', 'g.jaffry@chasse-maree.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Dominique Jannin', 'dominiquejannin9@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Karina Jeridi', 'karina_jeribi@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Nathjalene Jovignot ', 'lebc2228@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Céline Kahn', 'celine.kahn@oceanascommon.org');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jochen Krauth', 'jochen.krauth@sailcoop.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Marie Labussiere', 'Marie.labussiere@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Bernard LAGUERRE', 'aldoror@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('François LAGUERRE ', 'jurisbob@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('MP Labat', 'mariepierre.labat-camy@csdental.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean Baptiste Lacan', 'jeanbaptiste.lacan@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean Yves Legelvouit', 'leguel@outlook.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Louis Laigle', 'louis.laigle@neuf.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Lise Lambrecht', 'hamalyas@aol.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jacques Landron', 'jacques.landron@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Brigitte LANET', 'brigitte.lanet@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Alexandre lassale', 'lassalle.alexandre@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Chantal Laurent', 'cha.laurent.2@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Benoit Lavat', 'lavat.benoit@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Leurent Lavallet', '2l2telecnav@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Didier Le Diodic', 'Didier.LEDIODIC@bpgo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Patrick Lecoindre', 'patrick.lecoindre@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Franck Le devic', 'f.ledevic@free.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Olivier Le Diouris', 'olivier@lediouris.net');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Patrick Legait', 'patrick.legait@free.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Kim Anne Le Formal', 'kimanne.cherlock.leformal@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Yann Legrand', 'yann.legrand56@icloud.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Gerard Leiglon', 'modkozhasso@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Michel Lemeni', 'mlemeni@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean François Leray', 'litimat1@free.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Guy Le pecheur', 'lepecheur.g@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Benoit Leplatre', 'benoit.leplatre@icloud.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('claire Lesur Magois', 'claire.lesurmagois@icloud.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jose Levaillant', 'jose.levaillant@free.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('arthur Levaillant ', 'arthur.levaillant@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('jean Pierre Lode', 'jeanpierrelode55@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Loic Madeline', 'L.MADELINE@voilesetvoiliers.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Bernard Mallaret', 'voile193@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('antoine Mandet', 'an.mandet@hotmail.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Sophie Marquestaut', 'assotraverse@gmail.com');
-- INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Martine Martin', 'yl6591@hotmail.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean Marie Martzloff', 'jean-marie.martzolf@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Martin  Massot', 'martinmassot@hotmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jacopo Maretti', 'marrettijacopo@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Hélène Maurice', 'helemaurice@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Paul Melot', 'paul.melot@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Stéphane  Menuet', 'contact@oceane-voile.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Bernard Menuet', 'bmenuet@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Antoine Messonier', 'antoinemei@hotmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES(' Anne-Sophie Meysselle', 'Anne-Sophie.MEYSSELLE@bpgo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Thierry Michelin', 'thyol.michelin@cegetel.net');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Bernard Miens', 'bernardmiens@bbox.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Yves Milza', 'yves.milza@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Frédéric Minaud', 'minaud.frederic@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Patrick Moelo', 'pmoelo@thalos.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Brieuc Morin', 'brieuc.morin@sellor.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Guillaume  Morisseau', 'morisseauguillaume@msn.com');
-- INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Guillaume Morisseau', 'morisseauguillaume@msn.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean Pierre Mortreux', 'Jean-Pierre.Mortreux@asagao.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Francois Moulin', 'cfmoulin@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Nicolas Movio', 'nicolas.movio@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Nav Solidaires', 'nav.solidaire@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Damien NEGRIER', 'mukojiro123@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Yves Niort', 'yves1@netcourrier.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Patrick Onfray', 'pa.onfray@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jimmy  Pahun', '421jimmypahun@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Gabrielle Panetrat', 'panetrat@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Violaine PARCOT', 'vioparcot@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('jules Pasquier ', 'jules.pasquier02@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Etienne Pasquier ', 'grandcitronvert@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('jean Marie Patier', 'jmpatier@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Roland Payen', 'payen.roland@neuf.fr');
-- INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Sylvie Payen', 'payen.roland@neuf.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Chantal Pelhate', 'ch.pelhate@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Florent Pelhate', 'florent.pelhate@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Vincent Perrin Lacour', 'vplcom@free.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Dominique Petermuller', 'dominique.petermuller@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Gérard petit', 'maisonpetit@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Didier Pineau', 'didier.pineau@vulcani.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('alain Pichavant', 'alain.pichavant1@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('emelyne Pillet', 'etesek.pillet@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Fred Poissonnier', 'bcfre@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Zoé Pommier', 'pommier.zoe@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Sylvie Pons-Hermieu', 'sylvie.pons-hermieu@laposte.net');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('NOLWENN PORHIEL', 'nolwennporhiel@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Patrick  Potiron', 'patrick.potiron1@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('marine Prevet', 'marine.prevet@atelierkopal.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean Michel Prevet', 'prevet.jean-michel@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Pamela Prontinio', 'pabema@protonmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Leore Pujol', 'leore.pujol@oceanascommon.org');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Christophe Quesnel', 'christophequesnel06@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Benjamin Rasseneur', 'benjamin.rasseneur@laposte.net');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Bruno RECOULES', 'bruno@recoules-assurances.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Carole Redt', 'caroleredt@lilo.org');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Paul Reveillon', 'paul.reveillon@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Alix et Thomas Riviere', 'alixthomas.riviere@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Daniel Riviere', 'riviere.daniel@club.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Paul Rodionoff', 'paul.rodionoff@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Alain  Roig', 'antenor@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Christophe Roth', 'christophe_roth@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Sabine Roux de Bezieu', 'srb@fondationdelamer.org');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Yann Royer', 'yann.royer@sailcoop.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Fabien Saint-Supéry', 'fabienstsupery@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('JP Salaun', 'jp.salaun@laposte.net');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Claire Sanchez', 'sanchez.claire67@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Berenice Schell', 'berenice.schell@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Gregory Scmidt', 'm4vrick99@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Fred Sfiter', 'fred.shifter@proton.me');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Christophe Soares', 'christophesoares@navicom.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES(' Société Nautique de la Trinité-sur-mer', 'gestion@snt-voile.org');
-- INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Nav\' Solidaire', 'nav.solidaire@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Thibaud Soret', 'Thibaud.soret@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Carl Streissel', 'carl.streissel@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Benoît  Tarrière', 'tarriere.benoit@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Floriane Tchikladze', 'floriane.tchikladze@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('solene Tchikladzé', 'solene.tchikladze@yahoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Colin Torre ', 'torre.colin@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Gery  Trentesaux', 'gtrentesaux@gt-invest.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Bruno troublé', 'bruno.trouble2@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Jean Vacher', 'vacher.jean@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Gérard Vallée', 'vallgerard@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Christian Vernet ', 'vernetchris@sfr.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Mickaël VERRIER', 'mickael.verrier@lilo.org');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Sigrid Verwaerde', 'sigrid.verwaerde@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Remy Violet', 'remiviolet7@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Bruno Voisard', 'bvoisard@nauti-link.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Michel Vermeulen', 'michel.vermeulen1000@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Sophie Watter', 'contact.watter@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Lucas Weber', 'lucas.weber@live.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Ken Woehrle', 'ken.woehrle@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES(' ', 'vlb@phi-com.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('frederic Duthil', 'fd@technique-voile.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('Juliette ', 'droldelvalchat@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES(' ', 'mareflye@aol.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES(' ', 'margotpeutin@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES(' ', 'ollie.graffy@mylor.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('CORIOLAN Custom', 'pineau.audit@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('MONTOMBI NA40', 'cyrille@isaac-sibille.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('SCHLEMM Carter 39', 'jean-michel.hoarau@orange.fr');
-- INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('MARIC Carter 39', '421jimmypahun@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('HYLAS Carter 37', 'pj.jannin@passeurdecoute.fr');
-- INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('PORDIN NANCQ Carter 37', 'patrice.vnd@cegetel.net');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('PORDIN NANCQ ', 'halgattebruno@gmail.com');
-- INSERT INTO `nl-subscribers`(`name`, `email`) VALUES(' Carter 37', 'lavat.benoit@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('KOOKAÏ Carter 37', 'christian.haye2@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('CAVALIER SEUL Tina', 'edouard@daehn.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('SALANGANE Tina', 'jjo@ollu-avocat.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('BEL AMI Tina', 'huguesthomas@hotmail.fr');
-- INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('BILOU BELLE Tina', 'vallgerard@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('SAMOTH 3/4 Ton', 'norbertjandieleman@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('LOLITA 3/4 Ton', 'baly.yoann@neuf.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('BOTTLENECK Dingbat', 'jean-francois.daconceicao@orange.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('CAPELLA Custom', 'jp.lesieur@wanadoo.fr');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('SAPHIRE OF COWES Custom', 'tazpitarte@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('COQ GAULOIS Carter 37', 'vadantec.voile@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('GRAND FUN Carter 37', 'shakalban5@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('TIGRE Carter 37', 'ylambert@sparringpartner.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('MARMOUZ Carter 37', 'erwanmeriadec@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('PERSEPHONE Tina', 'pierre.favennec@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('BOLERO Tina', 'fouillard1@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('ESPRIT DE RUEIL Tina', 'info.yb.mx@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('LE ZOUAVE Carter 33', 'fredellier82@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('MARARAO Carter 33', 'mikabouvier72@gmail.com');
INSERT INTO `nl-subscribers`(`name`, `email`) VALUES('HEY JOE Carter 33', 'philippe.jacques.roux@orange.fr');
